[package]
name = "mc"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.15.3", default-features = false, features = ["bevy_asset", "bevy_core_pipeline", "bevy_pbr", "bevy_render", "bevy_text", "bevy_ui", "bevy_winit", "multi_threaded", "tonemapping_luts", "default_font", "x11", "png"] }

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
